# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
